### PR TITLE
Add package main to test.go

### PR DESCRIPTION
**Pull request by webkriativa-gabriel**
Description provided

### CODE REVIEW

**Review by Kelvin-Jesus — COMMENTED** [review]
Pls, remove the unnecessary return

**Review by Kelvin-Jesus — CHANGES_REQUESTED** [review]
Pls, remove the unnecessary return @webkriativa-gabriel 

- [ ] Should remove unnecessary return on function main.

**Comment by webkriativa-gabriel** [comment]
> 

Done

**Comment by webkriativa-gabriel** [comment]
> Pls, remove the unnecessary return @webkriativa-gabriel
> 
> * [ ]  Should remove unnecessary return on function main.

Done.

**Pull request merged**
